version: '3'

services:
  nano:
    image: ${DOCKER_REGISTRY}nanocurrency/nano:latest
    restart: unless-stopped
    volumes:
      - ./mnt:/root
    ports:
      - 7075:7075
      - 127.0.0.1:7076:7076
  monitor:
    image: ${DOCKER_REGISTRY}nanotools/nanonodemonitor
    restart: unless-stopped
    ports:
     - 80:80
    volumes:
     - ./mnt:/opt
